pipeline {

    agent any

    stages {
        stage('Install dependecies') {
            steps {
                echo "hola mundo"
		sh "docker -v"
		/*withEnv(['docker=/usr/local/bin/docker']) {
			sh "docker -v"
		}
		Este es un intento con el path directo de docker que
		configuré en mi jenkins y aún así no reconoce el 
		comando de docker 
		*/
            }
        }

    }
}