pipeline {

    agent any

    stages {
        stage('Install dependecies') {
            steps {
                echo "hola mundo"
		withEnv(['docker=/usr/local/bin/docker']) {
			sh "docker -v"
		}
            }
        }

    }
}