pipeline {

    agent any

    stages {
        stage('Build docker image') {
            steps {
                sh "sudo docker build . -t rest-market-${GIT_BRANCH}:1.0.0-${BUILD_NUMBER}"
            }
        }
        stage('Delete previous version docker container') {
            steps {
                sh "sudo docker rm -f rest-market-live"
                //&& echo "Container rest-market-live removed."
                //echo "Container rest-market-live does not exist."
            }
        }
        stage('Create and activate docker container for live version') {
            steps {
                sh "sudo docker run --name rest-market-live -d -p 3000:3000 rest-market-${GIT_BRANCH}:1.0.0-${BUILD_NUMBER}"
            }
        }
    }
    post {
        success {
            echo "All done."
            echo "Live version has been deployed."
        }
    }
}
